spring:
  application:
    name: Kotkit
  web:
    resources:
      static-locations: classpath:/nonexistent/

  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT}/kotkit
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION}

minio:
  endpoint: http://localhost:${MINIO_PORT_1}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucket: kotkit