spring:
  application:
    name: Kotkit
  web:
    resources:
      static-locations: classpath:/nonexistent/

  datasource:
      url: jdbc:mysql://localhost:3308/kotkit
      username: root
      password: 123

  jpa:
    hibernate:
      ddl-auto: none

security:
  jwt:
    secret-key: ZCQl6X6kQnI8PElWxA547cvvvzZSeRhQAzDe7ZYpOI0=
    expiration-time: 9999999999